name: Quality

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-node"
      - uses: "./.github/actions/setup-yarn"
      - uses: "./.github/actions/node-modules-cache"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  tests:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-node"
      - uses: "./.github/actions/setup-yarn"
      - uses: "./.github/actions/node-modules-cache"

      - name: Run tests
        run: yarn test
        working-directory: .

  typecheck:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-node"
      - uses: "./.github/actions/setup-yarn"
      - uses: "./.github/actions/node-modules-cache"

      - name: Typechecking
        run: yarn typecheck
        working-directory: .

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-node"
      - uses: "./.github/actions/setup-yarn"
      - uses: "./.github/actions/node-modules-cache"

      - name: Build applications
        run: yarn build
        working-directory: .
